// Generated by Bisonc++ V4.13.01 on Fri, 31 Mar 2017 14:33:02 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {296, 2}, // 1: program ->  declaration_list procedure_definition
     {297, 1}, // 2: declaration_list ->  procedure_declaration
     {297, 2}, // 3: declaration_list ->  variable_declaration_list procedure_declaration
     {297, 2}, // 4: declaration_list ->  procedure_declaration variable_declaration_list
     {299, 5}, // 5: procedure_declaration (VOID) ->  VOID NAME '(' ')' ';'
     {298, 9}, // 6: procedure_definition (NAME) ->  NAME '(' ')' #0001 '{' optional_variable_declaration_list #0002 statement_list '}'
     {300, 0}, // 7: #0001 ->  <empty>
     {301, 0}, // 8: #0002 ->  <empty>
     {302, 0}, // 9: optional_variable_declaration_list ->  <empty>
     {302, 1}, // 10: optional_variable_declaration_list ->  variable_declaration_list
     {303, 1}, // 11: variable_declaration_list ->  variable_declaration
     {303, 2}, // 12: variable_declaration_list ->  variable_declaration_list variable_declaration
     {304, 2}, // 13: variable_declaration (';') ->  declaration ';'
     {304, 4}, // 14: variable_declaration (',') ->  declaration ',' name_list ';'
     {305, 1}, // 15: name_list (NAME) ->  NAME
     {305, 3}, // 16: name_list (',') ->  name_list ',' NAME
     {306, 2}, // 17: declaration (INTEGER) ->  INTEGER NAME
     {306, 2}, // 18: declaration (FLOAT) ->  FLOAT NAME
     {307, 1}, // 19: statement ->  assignment_statement
     {307, 1}, // 20: statement ->  iterative_statement
     {307, 1}, // 21: statement ->  controlflow_statement
     {307, 3}, // 22: statement ('{') ->  '{' statement_list '}'
     {308, 0}, // 23: statement_list ->  <empty>
     {308, 2}, // 24: statement_list ->  statement_list statement
     {309, 5}, // 25: iterative_statement (WHILE) ->  WHILE '(' bool_expression ')' statement
     {309, 7}, // 26: iterative_statement (DO) ->  DO statement WHILE '(' bool_expression ')' ';'
     {310, 5}, // 27: controlflow_statement (IF) ->  IF '(' bool_expression ')' statement
     {310, 7}, // 28: controlflow_statement (IF) ->  IF '(' bool_expression ')' statement ELSE statement
     {311, 4}, // 29: assignment_statement (ASSIGN) ->  variable ASSIGN arith_expression ';'
     {312, 1}, // 30: bool_expression ->  relational_expression
     {312, 3}, // 31: bool_expression (AND) ->  bool_expression AND bool_expression
     {312, 3}, // 32: bool_expression (OR) ->  bool_expression OR bool_expression
     {312, 2}, // 33: bool_expression (NOT) ->  NOT bool_expression
     {312, 3}, // 34: bool_expression ('(') ->  '(' bool_expression ')'
     {313, 3}, // 35: relational_expression (LT) ->  operand LT operand
     {313, 3}, // 36: relational_expression (LT_EQ) ->  operand LT_EQ operand
     {313, 3}, // 37: relational_expression (GRT) ->  operand GRT operand
     {313, 3}, // 38: relational_expression (GRT_EQ) ->  operand GRT_EQ operand
     {313, 3}, // 39: relational_expression (EQ) ->  operand EQ operand
     {313, 3}, // 40: relational_expression (NOT_EQ) ->  operand NOT_EQ operand
     {314, 3}, // 41: arith_expression ('+') ->  operand '+' operand
     {314, 3}, // 42: arith_expression ('-') ->  operand '-' operand
     {314, 3}, // 43: arith_expression ('*') ->  operand '*' operand
     {314, 3}, // 44: arith_expression ('/') ->  operand '/' operand
     {314, 2}, // 45: arith_expression (UMINUS) ->  '-' operand
     {314, 3}, // 46: arith_expression ('(') ->  '(' operand ')'
     {314, 5}, // 47: arith_expression ('?') ->  bool_expression '?' operand ':' operand
     {314, 1}, // 48: arith_expression ->  expression_term
     {315, 1}, // 49: operand ->  arith_expression
     {316, 1}, // 50: expression_term ->  variable
     {316, 1}, // 51: expression_term ->  constant
     {317, 1}, // 52: variable (NAME) ->  NAME
     {318, 1}, // 53: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {318, 1}, // 54: constant (DOUBLE_NUMBER) ->  DOUBLE_NUMBER
     {319, 1}, // 55: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 10} },                             
    { {       296}, {  1} }, // program                  
    { {       297}, {  2} }, // declaration_list         
    { {       299}, {  3} }, // procedure_declaration    
    { {       303}, {  4} }, // variable_declaration_list
    { {       259}, {  5} }, // VOID                     
    { {       304}, {  6} }, // variable_declaration     
    { {       306}, {  7} }, // declaration              
    { {       260}, {  8} }, // INTEGER                  
    { {       261}, {  9} }, // FLOAT                    
    { {         0}, {  0} },                             
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, {  3} },                        
    { {       298}, { 10} }, // procedure_definition
    { {       267}, { 11} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  6} },                             
    { {     303}, { 12} }, // variable_declaration_list
    { {     304}, {  6} }, // variable_declaration     
    { {     306}, {  7} }, // declaration              
    { {     260}, {  8} }, // INTEGER                  
    { {     261}, {  9} }, // FLOAT                    
    { {       0}, { -2} },                             
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, {  7} },                         
    { {       299}, { 13} }, // procedure_declaration
    { {       304}, { 14} }, // variable_declaration 
    { {       259}, {  5} }, // VOID                 
    { {       306}, {  7} }, // declaration          
    { {       260}, {  8} }, // INTEGER              
    { {       261}, {  9} }, // FLOAT                
    { {         0}, {  0} },                         
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       267}, { 15} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_6[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 16} }, // ';'
    { {        44}, { 17} }, // ','
    { {         0}, {  0} },       
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       267}, { 18} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       267}, { 19} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_10[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 20} }, // '('
    { {         0}, {  0} },       
};

SR__ s_12[] =
{
    { { REQ_DEF}, {  5} },                        
    { {     304}, { 14} }, // variable_declaration
    { {     306}, {  7} }, // declaration         
    { {     260}, {  8} }, // INTEGER             
    { {     261}, {  9} }, // FLOAT               
    { {       0}, { -4} },                        
};

SR__ s_13[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 21} }, // '('
    { {         0}, {  0} },       
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       305}, { 22} }, // name_list
    { {       267}, { 23} }, // NAME     
    { {         0}, {  0} },             
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 24} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 25} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 26} }, // ';'
    { {        44}, { 27} }, // ','
    { {         0}, {  0} },       
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_24[] =
{
    { { DEF_RED}, {  2} },         
    { {     300}, { 28} }, // #0001
    { {       0}, { -7} },         
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 29} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       267}, { 30} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 31} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_29[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_31[] =
{
    { { REQ_DEF}, {  7} },                                      
    { {     302}, { 32} }, // optional_variable_declaration_list
    { {     303}, { 33} }, // variable_declaration_list         
    { {     304}, {  6} }, // variable_declaration              
    { {     306}, {  7} }, // declaration                       
    { {     260}, {  8} }, // INTEGER                           
    { {     261}, {  9} }, // FLOAT                             
    { {       0}, { -9} },                                      
};

SR__ s_32[] =
{
    { { DEF_RED}, {  2} },         
    { {     301}, { 34} }, // #0002
    { {       0}, { -8} },         
};

SR__ s_33[] =
{
    { { REQ_DEF}, {   5} },                        
    { {     304}, {  14} }, // variable_declaration
    { {     306}, {   7} }, // declaration         
    { {     260}, {   8} }, // INTEGER             
    { {     261}, {   9} }, // FLOAT               
    { {       0}, { -10} },                        
};

SR__ s_34[] =
{
    { { DEF_RED}, {   2} },                  
    { {     308}, {  35} }, // statement_list
    { {       0}, { -23} },                  
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, { 12} },                         
    { {       125}, { 36} }, // '}'                  
    { {       307}, { 37} }, // statement            
    { {       311}, { 38} }, // assignment_statement 
    { {       309}, { 39} }, // iterative_statement  
    { {       310}, { 40} }, // controlflow_statement
    { {       123}, { 41} }, // '{'                  
    { {       317}, { 42} }, // variable             
    { {       264}, { 43} }, // WHILE                
    { {       263}, { 44} }, // DO                   
    { {       265}, { 45} }, // IF                   
    { {       267}, { 46} }, // NAME                 
    { {         0}, {  0} },                         
};

SR__ s_36[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   2} },                  
    { {     308}, {  47} }, // statement_list
    { {       0}, { -23} },                  
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       262}, { 48} }, // ASSIGN
    { {         0}, {  0} },          
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 49} }, // '('
    { {         0}, {  0} },       
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 11} },                         
    { {       307}, { 50} }, // statement            
    { {       311}, { 38} }, // assignment_statement 
    { {       309}, { 39} }, // iterative_statement  
    { {       310}, { 40} }, // controlflow_statement
    { {       123}, { 41} }, // '{'                  
    { {       317}, { 42} }, // variable             
    { {       264}, { 43} }, // WHILE                
    { {       263}, { 44} }, // DO                   
    { {       265}, { 45} }, // IF                   
    { {       267}, { 46} }, // NAME                 
    { {         0}, {  0} },                         
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 51} }, // '('
    { {         0}, {  0} },       
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, { 12} },                         
    { {       125}, { 52} }, // '}'                  
    { {       307}, { 37} }, // statement            
    { {       311}, { 38} }, // assignment_statement 
    { {       309}, { 39} }, // iterative_statement  
    { {       310}, { 40} }, // controlflow_statement
    { {       123}, { 41} }, // '{'                  
    { {       317}, { 42} }, // variable             
    { {       264}, { 43} }, // WHILE                
    { {       263}, { 44} }, // DO                   
    { {       265}, { 45} }, // IF                   
    { {       267}, { 46} }, // NAME                 
    { {         0}, {  0} },                         
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       314}, { 53} }, // arith_expression     
    { {       315}, { 54} }, // operand              
    { {        45}, { 55} }, // '-'                  
    { {        40}, { 56} }, // '('                  
    { {       312}, { 57} }, // bool_expression      
    { {       316}, { 58} }, // expression_term      
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       312}, { 65} }, // bool_expression      
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {        40}, { 56} }, // '('                  
    { {       315}, { 54} }, // operand              
    { {       314}, { 66} }, // arith_expression     
    { {        45}, { 55} }, // '-'                  
    { {       316}, { 58} }, // expression_term      
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       264}, { 67} }, // WHILE
    { {         0}, {  0} },         
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       312}, { 68} }, // bool_expression      
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {        40}, { 56} }, // '('                  
    { {       315}, { 54} }, // operand              
    { {       314}, { 66} }, // arith_expression     
    { {        45}, { 55} }, // '-'                  
    { {       316}, { 58} }, // expression_term      
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_53[] =
{
    { { REQ_DEF}, {   2} },       
    { {      59}, {  69} }, // ';'
    { {       0}, { -49} },       
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, { 11} },          
    { {        43}, { 70} }, // '+'   
    { {        45}, { 71} }, // '-'   
    { {        42}, { 72} }, // '*'   
    { {        47}, { 73} }, // '/'   
    { {       273}, { 74} }, // LT    
    { {       274}, { 75} }, // LT_EQ 
    { {       275}, { 76} }, // GRT   
    { {       276}, { 77} }, // GRT_EQ
    { {       272}, { 78} }, // EQ    
    { {       271}, { 79} }, // NOT_EQ
    { {         0}, {  0} },          
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       315}, { 80} }, // operand              
    { {       314}, { 66} }, // arith_expression     
    { {        45}, { 55} }, // '-'                  
    { {        40}, { 56} }, // '('                  
    { {       312}, { 57} }, // bool_expression      
    { {       316}, { 58} }, // expression_term      
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       315}, { 81} }, // operand              
    { {       312}, { 82} }, // bool_expression      
    { {       314}, { 66} }, // arith_expression     
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {        40}, { 56} }, // '('                  
    { {        45}, { 55} }, // '-'                  
    { {       316}, { 58} }, // expression_term      
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  4} },       
    { {        63}, { 83} }, // '?'
    { {       270}, { 84} }, // AND
    { {       269}, { 85} }, // OR 
    { {         0}, {  0} },       
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       312}, { 86} }, // bool_expression      
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {        40}, { 56} }, // '('                  
    { {       315}, { 54} }, // operand              
    { {       314}, { 66} }, // arith_expression     
    { {        45}, { 55} }, // '-'                  
    { {       316}, { 58} }, // expression_term      
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  5} },       
    { {        41}, { 87} }, // ')'
    { {       270}, { 84} }, // AND
    { {       269}, { 85} }, // OR 
    { {        63}, { 83} }, // '?'
    { {         0}, {  0} },       
};

SR__ s_66[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 88} }, // '('
    { {         0}, {  0} },       
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, {  5} },       
    { {        41}, { 89} }, // ')'
    { {       270}, { 84} }, // AND
    { {       269}, { 85} }, // OR 
    { {        63}, { 83} }, // '?'
    { {         0}, {  0} },       
};

SR__ s_69[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       315}, { 90} }, // operand              
    { {       314}, { 66} }, // arith_expression     
    { {        45}, { 55} }, // '-'                  
    { {        40}, { 56} }, // '('                  
    { {       312}, { 57} }, // bool_expression      
    { {       316}, { 58} }, // expression_term      
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       315}, { 91} }, // operand              
    { {       314}, { 66} }, // arith_expression     
    { {        45}, { 55} }, // '-'                  
    { {        40}, { 56} }, // '('                  
    { {       312}, { 57} }, // bool_expression      
    { {       316}, { 58} }, // expression_term      
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       315}, { 92} }, // operand              
    { {       314}, { 66} }, // arith_expression     
    { {        45}, { 55} }, // '-'                  
    { {        40}, { 56} }, // '('                  
    { {       312}, { 57} }, // bool_expression      
    { {       316}, { 58} }, // expression_term      
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       315}, { 93} }, // operand              
    { {       314}, { 66} }, // arith_expression     
    { {        45}, { 55} }, // '-'                  
    { {        40}, { 56} }, // '('                  
    { {       312}, { 57} }, // bool_expression      
    { {       316}, { 58} }, // expression_term      
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       315}, { 94} }, // operand              
    { {       314}, { 66} }, // arith_expression     
    { {        45}, { 55} }, // '-'                  
    { {        40}, { 56} }, // '('                  
    { {       312}, { 57} }, // bool_expression      
    { {       316}, { 58} }, // expression_term      
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       315}, { 95} }, // operand              
    { {       314}, { 66} }, // arith_expression     
    { {        45}, { 55} }, // '-'                  
    { {        40}, { 56} }, // '('                  
    { {       312}, { 57} }, // bool_expression      
    { {       316}, { 58} }, // expression_term      
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       315}, { 96} }, // operand              
    { {       314}, { 66} }, // arith_expression     
    { {        45}, { 55} }, // '-'                  
    { {        40}, { 56} }, // '('                  
    { {       312}, { 57} }, // bool_expression      
    { {       316}, { 58} }, // expression_term      
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       315}, { 97} }, // operand              
    { {       314}, { 66} }, // arith_expression     
    { {        45}, { 55} }, // '-'                  
    { {        40}, { 56} }, // '('                  
    { {       312}, { 57} }, // bool_expression      
    { {       316}, { 58} }, // expression_term      
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       315}, { 98} }, // operand              
    { {       314}, { 66} }, // arith_expression     
    { {        45}, { 55} }, // '-'                  
    { {        40}, { 56} }, // '('                  
    { {       312}, { 57} }, // bool_expression      
    { {       316}, { 58} }, // expression_term      
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       315}, { 99} }, // operand              
    { {       314}, { 66} }, // arith_expression     
    { {        45}, { 55} }, // '-'                  
    { {        40}, { 56} }, // '('                  
    { {       312}, { 57} }, // bool_expression      
    { {       316}, { 58} }, // expression_term      
    { {       313}, { 59} }, // relational_expression
    { {       277}, { 60} }, // NOT                  
    { {       317}, { 61} }, // variable             
    { {       318}, { 62} }, // constant             
    { {       267}, { 46} }, // NAME                 
    { {       257}, { 63} }, // INTEGER_NUMBER       
    { {       258}, { 64} }, // DOUBLE_NUMBER        
    { {         0}, {  0} },                         
};

SR__ s_80[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {  12} },          
    { {        41}, { 100} }, // ')'   
    { {        43}, {  70} }, // '+'   
    { {        45}, {  71} }, // '-'   
    { {        42}, {  72} }, // '*'   
    { {        47}, {  73} }, // '/'   
    { {       273}, {  74} }, // LT    
    { {       274}, {  75} }, // LT_EQ 
    { {       275}, {  76} }, // GRT   
    { {       276}, {  77} }, // GRT_EQ
    { {       272}, {  78} }, // EQ    
    { {       271}, {  79} }, // NOT_EQ
    { {         0}, {   0} },          
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {   5} },       
    { {        41}, { 101} }, // ')'
    { {       270}, {  84} }, // AND
    { {       269}, {  85} }, // OR 
    { {        63}, {  83} }, // '?'
    { {         0}, {   0} },       
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {  14} },                         
    { {       315}, { 102} }, // operand              
    { {       314}, {  66} }, // arith_expression     
    { {        45}, {  55} }, // '-'                  
    { {        40}, {  56} }, // '('                  
    { {       312}, {  57} }, // bool_expression      
    { {       316}, {  58} }, // expression_term      
    { {       313}, {  59} }, // relational_expression
    { {       277}, {  60} }, // NOT                  
    { {       317}, {  61} }, // variable             
    { {       318}, {  62} }, // constant             
    { {       267}, {  46} }, // NAME                 
    { {       257}, {  63} }, // INTEGER_NUMBER       
    { {       258}, {  64} }, // DOUBLE_NUMBER        
    { {         0}, {   0} },                         
};

SR__ s_84[] =
{
    { { REQ_TOKEN}, {  14} },                         
    { {       312}, { 103} }, // bool_expression      
    { {       313}, {  59} }, // relational_expression
    { {       277}, {  60} }, // NOT                  
    { {        40}, {  56} }, // '('                  
    { {       315}, {  54} }, // operand              
    { {       314}, {  66} }, // arith_expression     
    { {        45}, {  55} }, // '-'                  
    { {       316}, {  58} }, // expression_term      
    { {       317}, {  61} }, // variable             
    { {       318}, {  62} }, // constant             
    { {       267}, {  46} }, // NAME                 
    { {       257}, {  63} }, // INTEGER_NUMBER       
    { {       258}, {  64} }, // DOUBLE_NUMBER        
    { {         0}, {   0} },                         
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  14} },                         
    { {       312}, { 104} }, // bool_expression      
    { {       313}, {  59} }, // relational_expression
    { {       277}, {  60} }, // NOT                  
    { {        40}, {  56} }, // '('                  
    { {       315}, {  54} }, // operand              
    { {       314}, {  66} }, // arith_expression     
    { {        45}, {  55} }, // '-'                  
    { {       316}, {  58} }, // expression_term      
    { {       317}, {  61} }, // variable             
    { {       318}, {  62} }, // constant             
    { {       267}, {  46} }, // NAME                 
    { {       257}, {  63} }, // INTEGER_NUMBER       
    { {       258}, {  64} }, // DOUBLE_NUMBER        
    { {         0}, {   0} },                         
};

SR__ s_86[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {  11} },                         
    { {       307}, { 105} }, // statement            
    { {       311}, {  38} }, // assignment_statement 
    { {       309}, {  39} }, // iterative_statement  
    { {       310}, {  40} }, // controlflow_statement
    { {       123}, {  41} }, // '{'                  
    { {       317}, {  42} }, // variable             
    { {       264}, {  43} }, // WHILE                
    { {       263}, {  44} }, // DO                   
    { {       265}, {  45} }, // IF                   
    { {       267}, {  46} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {  14} },                         
    { {       312}, { 106} }, // bool_expression      
    { {       313}, {  59} }, // relational_expression
    { {       277}, {  60} }, // NOT                  
    { {        40}, {  56} }, // '('                  
    { {       315}, {  54} }, // operand              
    { {       314}, {  66} }, // arith_expression     
    { {        45}, {  55} }, // '-'                  
    { {       316}, {  58} }, // expression_term      
    { {       317}, {  61} }, // variable             
    { {       318}, {  62} }, // constant             
    { {       267}, {  46} }, // NAME                 
    { {       257}, {  63} }, // INTEGER_NUMBER       
    { {       258}, {  64} }, // DOUBLE_NUMBER        
    { {         0}, {   0} },                         
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {  11} },                         
    { {       307}, { 107} }, // statement            
    { {       311}, {  38} }, // assignment_statement 
    { {       309}, {  39} }, // iterative_statement  
    { {       310}, {  40} }, // controlflow_statement
    { {       123}, {  41} }, // '{'                  
    { {       317}, {  42} }, // variable             
    { {       264}, {  43} }, // WHILE                
    { {       263}, {  44} }, // DO                   
    { {       265}, {  45} }, // IF                   
    { {       267}, {  46} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_90[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  72} }, // '*'
    { {      47}, {  73} }, // '/'
    { {       0}, { -41} },       
};

SR__ s_91[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  72} }, // '*'
    { {      47}, {  73} }, // '/'
    { {       0}, { -42} },       
};

SR__ s_92[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_93[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_94[] =
{
    { { REQ_DEF}, {  11} },          
    { {      43}, {  70} }, // '+'   
    { {      45}, {  71} }, // '-'   
    { {      42}, {  72} }, // '*'   
    { {      47}, {  73} }, // '/'   
    { {     273}, {  74} }, // LT    
    { {     274}, {  75} }, // LT_EQ 
    { {     275}, {  76} }, // GRT   
    { {     276}, {  77} }, // GRT_EQ
    { {     272}, {  78} }, // EQ    
    { {     271}, {  79} }, // NOT_EQ
    { {       0}, { -35} },          
};

SR__ s_95[] =
{
    { { REQ_DEF}, {  11} },          
    { {      43}, {  70} }, // '+'   
    { {      45}, {  71} }, // '-'   
    { {      42}, {  72} }, // '*'   
    { {      47}, {  73} }, // '/'   
    { {     273}, {  74} }, // LT    
    { {     274}, {  75} }, // LT_EQ 
    { {     275}, {  76} }, // GRT   
    { {     276}, {  77} }, // GRT_EQ
    { {     272}, {  78} }, // EQ    
    { {     271}, {  79} }, // NOT_EQ
    { {       0}, { -36} },          
};

SR__ s_96[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  70} }, // '+'
    { {      45}, {  71} }, // '-'
    { {      42}, {  72} }, // '*'
    { {      47}, {  73} }, // '/'
    { {       0}, { -37} },       
};

SR__ s_97[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  70} }, // '+'
    { {      45}, {  71} }, // '-'
    { {      42}, {  72} }, // '*'
    { {      47}, {  73} }, // '/'
    { {       0}, { -38} },       
};

SR__ s_98[] =
{
    { { REQ_DEF}, {   9} },          
    { {      43}, {  70} }, // '+'   
    { {      45}, {  71} }, // '-'   
    { {      42}, {  72} }, // '*'   
    { {      47}, {  73} }, // '/'   
    { {     273}, {  74} }, // LT    
    { {     274}, {  75} }, // LT_EQ 
    { {     275}, {  76} }, // GRT   
    { {     276}, {  77} }, // GRT_EQ
    { {       0}, { -39} },          
};

SR__ s_99[] =
{
    { { REQ_DEF}, {   9} },          
    { {      43}, {  70} }, // '+'   
    { {      45}, {  71} }, // '-'   
    { {      42}, {  72} }, // '*'   
    { {      47}, {  73} }, // '/'   
    { {     273}, {  74} }, // LT    
    { {     274}, {  75} }, // LT_EQ 
    { {     275}, {  76} }, // GRT   
    { {     276}, {  77} }, // GRT_EQ
    { {       0}, { -40} },          
};

SR__ s_100[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_101[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {  12} },          
    { {        58}, { 108} }, // ':'   
    { {        43}, {  70} }, // '+'   
    { {        45}, {  71} }, // '-'   
    { {        42}, {  72} }, // '*'   
    { {        47}, {  73} }, // '/'   
    { {       273}, {  74} }, // LT    
    { {       274}, {  75} }, // LT_EQ 
    { {       275}, {  76} }, // GRT   
    { {       276}, {  77} }, // GRT_EQ
    { {       272}, {  78} }, // EQ    
    { {       271}, {  79} }, // NOT_EQ
    { {         0}, {   0} },          
};

SR__ s_103[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_104[] =
{
    { { REQ_DEF}, {   2} },       
    { {     270}, {  84} }, // AND
    { {       0}, { -32} },       
};

SR__ s_105[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_106[] =
{
    { { REQ_TOKEN}, {   5} },       
    { {        41}, { 109} }, // ')'
    { {       270}, {  84} }, // AND
    { {       269}, {  85} }, // OR 
    { {        63}, {  83} }, // '?'
    { {         0}, {   0} },       
};

SR__ s_107[] =
{
    { { REQ_DEF}, {   2} },        
    { {     268}, { 110} }, // ELSE
    { {       0}, { -27} },        
};

SR__ s_108[] =
{
    { { REQ_TOKEN}, {  14} },                         
    { {       315}, { 111} }, // operand              
    { {       314}, {  66} }, // arith_expression     
    { {        45}, {  55} }, // '-'                  
    { {        40}, {  56} }, // '('                  
    { {       312}, {  57} }, // bool_expression      
    { {       316}, {  58} }, // expression_term      
    { {       313}, {  59} }, // relational_expression
    { {       277}, {  60} }, // NOT                  
    { {       317}, {  61} }, // variable             
    { {       318}, {  62} }, // constant             
    { {       267}, {  46} }, // NAME                 
    { {       257}, {  63} }, // INTEGER_NUMBER       
    { {       258}, {  64} }, // DOUBLE_NUMBER        
    { {         0}, {   0} },                         
};

SR__ s_109[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 112} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_110[] =
{
    { { REQ_TOKEN}, {  11} },                         
    { {       307}, { 113} }, // statement            
    { {       311}, {  38} }, // assignment_statement 
    { {       309}, {  39} }, // iterative_statement  
    { {       310}, {  40} }, // controlflow_statement
    { {       123}, {  41} }, // '{'                  
    { {       317}, {  42} }, // variable             
    { {       264}, {  43} }, // WHILE                
    { {       263}, {  44} }, // DO                   
    { {       265}, {  45} }, // IF                   
    { {       267}, {  46} }, // NAME                 
    { {         0}, {   0} },                         
};

SR__ s_111[] =
{
    { { REQ_DEF}, {  11} },          
    { {      43}, {  70} }, // '+'   
    { {      45}, {  71} }, // '-'   
    { {      42}, {  72} }, // '*'   
    { {      47}, {  73} }, // '/'   
    { {     273}, {  74} }, // LT    
    { {     274}, {  75} }, // LT_EQ 
    { {     275}, {  76} }, // GRT   
    { {     276}, {  77} }, // GRT_EQ
    { {     272}, {  78} }, // EQ    
    { {     271}, {  79} }, // NOT_EQ
    { {       0}, { -47} },          
};

SR__ s_112[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_113[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

// $insert defaultactionreturn
                            // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 70 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         program_object.set_procedure(current_procedure, get_line_number());
         program_object.global_list_in_proc_check();
         }
         }
        break;

        case 2:
#line 83 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = new Symbol_Table();
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 3:
#line 93 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = d_vsp__[-1].symbol_table;
         CHECK_INVARIANT((global_table != NULL), "Global declarations cannot be null");
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 4:
#line 106 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = d_vsp__[0].symbol_table;
         CHECK_INVARIANT((global_table != NULL), "Global declarations cannot be null");
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 5:
#line 120 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-3].string_value != NULL), "Procedure name cannot be null");
         CHECK_INVARIANT((*d_vsp__[-3].string_value == "main"), "Procedure name must be main in declaration");
         }
         }
        break;

        case 6:
#line 163 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Sequence_Ast* seq = d_vsp__[-1].sequence_ast;
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         CHECK_INVARIANT((seq != NULL), "statement list cannot be null");
         current_procedure->set_sequence_ast(*seq);
         }
         }
        break;

        case 7:
#line 131 "parser.yy"
        d_val__ = d_vsp__[-2];
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-2].string_value != NULL), "Procedure name cannot be null");
         CHECK_INVARIANT((*d_vsp__[-2].string_value == "main"), "Procedure name must be main");
         string proc_name = *d_vsp__[-2].string_value;
         current_procedure = new Procedure(void_data_type, proc_name, get_line_number());
         CHECK_INPUT ((program_object.variable_in_symbol_list_check(proc_name) == false),
         "Procedure name cannot be same as global variable", get_line_number());
         }
         }
        break;

        case 8:
#line 147 "parser.yy"
        d_val__ = d_vsp__[-5];
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         Symbol_Table * local_table = d_vsp__[0].symbol_table;
         if (local_table == NULL)
         local_table = new Symbol_Table();
         current_procedure->set_local_list(*local_table);
         }
         }
        break;

        case 9:
#line 177 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.symbol_table = NULL;
         }
         }
        break;

        case 10:
#line 185 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].symbol_table != NULL), "Declaration statement list cannot be null here");
         d_val__.symbol_table = d_vsp__[0].symbol_table;
         }
         }
        break;

        case 11:
#line 197 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * decl_list = new Symbol_Table();
         list<Symbol_Table_Entry *> * decl_stmt = d_vsp__[0].s_list;
         CHECK_INVARIANT((decl_stmt != NULL), "The declaration statement cannot be null");
         
         for (list<Symbol_Table_Entry *>::iterator it = decl_stmt->begin(); it != decl_stmt->end(); it++)
         {
         string decl_name = (*it)->get_variable_name();
         CHECK_INPUT((program_object.variable_proc_name_check(decl_name) == false),
         "Procedure name cannot be same as the variable name", get_line_number());
         if(current_procedure != NULL)
         {
         CHECK_INPUT((current_procedure->get_proc_name() != decl_name),
         "Variable name cannot be same as procedure name", get_line_number());
         }
         CHECK_INPUT(((decl_list)->variable_in_symbol_list_check(decl_name) == false), 
         "Variable is declared twice", get_line_number());
         decl_list->push_symbol(*it);
         }
         d_val__.symbol_table = decl_list;
         }
         }
        break;

        case 12:
#line 223 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * decl_list = d_vsp__[-1].symbol_table;
         list<Symbol_Table_Entry *> * decl_stmt = d_vsp__[0].s_list;
         CHECK_INVARIANT((decl_stmt != NULL), "The declaration statement cannot be null");
         CHECK_INVARIANT((decl_list != NULL), "The declaration statement list cannot be null");
         for (list<Symbol_Table_Entry *>::iterator it = decl_stmt->begin(); it != decl_stmt->end(); it++)
         {
         string decl_name = (*it)->get_variable_name();
         CHECK_INPUT((program_object.variable_proc_name_check(decl_name) == false),
         "Procedure name cannot be same as the variable name", get_line_number());
         if(current_procedure != NULL)
         {
         CHECK_INPUT((current_procedure->get_proc_name() != decl_name),
         "Variable name cannot be same as procedure name", get_line_number());
         }
         CHECK_INPUT(((decl_list)->variable_in_symbol_list_check(decl_name) == false), 
         "Variable is declared twice", get_line_number());
         decl_list->push_symbol(*it);
         }
         d_val__.symbol_table = decl_list;
         }
         }
        break;

        case 13:
#line 251 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         pair<Data_Type, string> * decl = d_vsp__[-1].decl;
         CHECK_INVARIANT((decl != NULL), "Declaration cannot be null");
         Data_Type type = decl->first;
         string decl_name = decl->second;
         list<Symbol_Table_Entry *> * decl_list = new list<Symbol_Table_Entry *>;
         decl_list -> push_back(new Symbol_Table_Entry(decl_name, type, get_line_number()));
         d_val__.s_list = decl_list;
         }
         }
        break;

        case 14:
#line 269 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         if(NOT_ONLY_PARSE)
         {
         pair<Data_Type, string> * decl = d_vsp__[-3].decl;
         CHECK_INVARIANT((decl != NULL), "Declaration cannot be null");
         Data_Type type = decl -> first;
         string decl_name = decl -> second;
         list<Symbol_Table_Entry *> * decl_list = new list<Symbol_Table_Entry *>;
         decl_list -> push_back(new Symbol_Table_Entry(decl_name, type, get_line_number()));
         list<string> * name_list = d_vsp__[-1].decl_list1;
         for( list<string>::iterator it = name_list -> begin(); it != name_list ->end(); ++it )
         {
         decl_name = *it;
         decl_list -> push_back( new Symbol_Table_Entry(decl_name, type, get_line_number() ) );
         }
         d_val__.s_list = decl_list;
         }
         }
         }
        break;

        case 15:
#line 301 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "Name cannot be null");
         list<string> * decl_list = new list<string>;
         string name = *d_vsp__[0].string_value;
         
         decl_list -> push_back( name );
         d_val__.decl_list1 = decl_list;
         }
         }
        break;

        case 16:
#line 315 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "Name cannot be null");
         string name = *d_vsp__[0].string_value;
         d_vsp__[-2].decl_list1 -> push_back( name );
         d_val__.decl_list1 = d_vsp__[-2].decl_list1;
         }
         }
        break;

        case 17:
#line 330 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "NAME cannot be null");
         Data_Type i_type = int_data_type;
         string name = *d_vsp__[0].string_value;
         
         pair<Data_Type, string> * decl = new pair<Data_Type, string>(i_type, name);
         d_val__.decl = decl;
         }
         }
        break;

        case 18:
#line 344 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "NAME cannot be null");
         Data_Type d_type = double_data_type;
         string name = *d_vsp__[0].string_value;
         
         pair<Data_Type, string> * decl = new pair<Data_Type, string>(d_type, name);
         d_val__.decl = decl;
         }
         }
        break;

        case 19:
#line 360 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 20:
#line 368 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 21:
#line 376 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 22:
#line 384 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[-1].sequence_ast;
         }
         }
        break;

        case 23:
#line 393 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         { 
         d_val__.sequence_ast = new Sequence_Ast(get_line_number());
         }
         }
        break;

        case 24:
#line 401 "parser.yy"
        {
         if(NOT_ONLY_PARSE)
         {
         d_vsp__[-1].sequence_ast->ast_push_back(d_vsp__[0].ast);
         d_val__.sequence_ast = d_vsp__[-1].sequence_ast;
         }
         }
        break;

        case 25:
#line 412 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-2].ast != NULL), "Condition cannot be null");
         Ast * iteration_stmt = new Iteration_Statement_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, get_line_number(), false);
         d_val__.ast = iteration_stmt;
         }
         }
        break;

        case 26:
#line 424 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-2].ast != NULL), "Condition cannot be null");
         Ast * iteration_stmt = new Iteration_Statement_Ast(d_vsp__[-2].ast, d_vsp__[-5].ast , get_line_number(), true);
         d_val__.ast = iteration_stmt;
         }
         }
        break;

        case 27:
#line 438 "parser.yy"
        {
         CHECK_INVARIANT((d_vsp__[-2].ast != NULL), "Condition cannot be null");
         Ast * else_part = new Sequence_Ast(get_line_number());
         Ast * control_stmt = new Selection_Statement_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, else_part , get_line_number());
         d_val__.ast = control_stmt;
         }
        break;

        case 28:
#line 448 "parser.yy"
        {
         CHECK_INVARIANT((d_vsp__[-4].ast != NULL), "Condition cannot be null");
         Ast * control_stmt = new Selection_Statement_Ast(d_vsp__[-4].ast, d_vsp__[-2].ast, d_vsp__[0].ast , get_line_number());
         d_val__.ast = control_stmt;
         }
        break;

        case 29:
#line 459 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-3].ast != NULL) && (d_vsp__[-1].ast != NULL)), "lhs/rhs cannot be null");
         Ast *lhs = d_vsp__[-3].ast;
         Ast *rhs = d_vsp__[-1].ast;
         Ast * assignment_stmt = new Assignment_Ast(lhs, rhs, get_line_number());
         assignment_stmt->check_ast();
         d_val__.ast = assignment_stmt;
         }
         }
        break;

        case 30:
#line 476 "parser.yy"
        {
         CHECK_INVARIANT((d_vsp__[0].ast != NULL), "relational expression cannot be null");
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 31:
#line 482 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * and_stmt = new Boolean_Expr_Ast(d_vsp__[-2].ast, boolean_and, d_vsp__[0].ast, get_line_number());
         and_stmt->check_ast();
         d_val__.ast = and_stmt;
         }
         }
        break;

        case 32:
#line 495 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * or_stmt = new Boolean_Expr_Ast(d_vsp__[-2].ast, boolean_or, d_vsp__[0].ast, get_line_number());
         or_stmt->check_ast();
         d_val__.ast = or_stmt;
         }
         }
        break;

        case 33:
#line 508 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].ast != NULL), "rhs cannot be null");
         Ast * not_stmt = new Boolean_Expr_Ast(NULL, boolean_not, d_vsp__[0].ast, get_line_number());
         not_stmt->check_ast();
         d_val__.ast = not_stmt;
         }
         }
        break;

        case 34:
#line 521 "parser.yy"
        {
         CHECK_INVARIANT((d_vsp__[-1].ast != NULL), "bool expression cannot be null");
         d_val__.ast = d_vsp__[-1].ast;
         }
        break;

        case 35:
#line 529 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * lessthan_stmt = new Relational_Expr_Ast(d_vsp__[-2].ast, less_than, d_vsp__[0].ast, get_line_number());
         lessthan_stmt->check_ast();
         d_val__.ast = lessthan_stmt;
         }
         }
        break;

        case 36:
#line 542 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * lessthaneq_stmt = new Relational_Expr_Ast(d_vsp__[-2].ast, less_equalto, d_vsp__[0].ast, get_line_number());
         lessthaneq_stmt->check_ast();
         d_val__.ast = lessthaneq_stmt;
         }
         }
        break;

        case 37:
#line 555 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * greaterthan_stmt = new Relational_Expr_Ast(d_vsp__[-2].ast, greater_than, d_vsp__[0].ast, get_line_number());
         greaterthan_stmt->check_ast();
         d_val__.ast = greaterthan_stmt;
         }
         }
        break;

        case 38:
#line 568 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * greaterthaneq_stmt = new Relational_Expr_Ast(d_vsp__[-2].ast, greater_equalto, d_vsp__[0].ast, get_line_number());
         greaterthaneq_stmt->check_ast();
         d_val__.ast = greaterthaneq_stmt;
         }
         }
        break;

        case 39:
#line 581 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * eq_stmt = new Relational_Expr_Ast(d_vsp__[-2].ast, equalto, d_vsp__[0].ast, get_line_number());
         eq_stmt->check_ast();
         d_val__.ast = eq_stmt;
         }
         }
        break;

        case 40:
#line 594 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * noteq_stmt = new Relational_Expr_Ast(d_vsp__[-2].ast, not_equalto, d_vsp__[0].ast, get_line_number());
         noteq_stmt->check_ast();
         d_val__.ast = noteq_stmt;
         }
         }
        break;

        case 41:
#line 612 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * plus_stmt = new Plus_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, get_line_number());
         plus_stmt->check_ast();
         d_val__.ast = plus_stmt;
         }
         }
        break;

        case 42:
#line 625 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * minus_stmt = new Minus_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, get_line_number());
         minus_stmt->check_ast();
         d_val__.ast = minus_stmt;
         }
         }
        break;

        case 43:
#line 638 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * mult_stmt = new Mult_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, get_line_number());
         mult_stmt->check_ast();
         d_val__.ast = mult_stmt;
         }
         }
        break;

        case 44:
#line 651 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * divide_stmt = new Divide_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, get_line_number());
         divide_stmt->check_ast();
         d_val__.ast = divide_stmt;
         }
         }
        break;

        case 45:
#line 664 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].ast != NULL), "operand cannot be null");
         Ast * uminus_stmt = new UMinus_Ast(d_vsp__[0].ast, NULL, get_line_number());
         d_val__.ast = uminus_stmt;
         }
         }
        break;

        case 46:
#line 675 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[-1].ast;
         }
         }
        break;

        case 47:
#line 683 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-4].ast != NULL) && (d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "operands cannot be null");
         Ast * control_stmt = new Conditional_Operator_Ast(d_vsp__[-4].ast, d_vsp__[-2].ast, d_vsp__[0].ast , get_line_number());
         control_stmt->check_ast();
         d_val__.ast = control_stmt; 
         }
         }
        break;

        case 48:
#line 695 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 49:
#line 705 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 50:
#line 715 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 51:
#line 723 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 52:
#line 733 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table_Entry * var_table_entry;
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "Variable name cannot be null");
         if (current_procedure->variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = &(current_procedure->get_symbol_table_entry(*d_vsp__[0].string_value));
         else if (program_object.variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = &(program_object.get_symbol_table_entry(*d_vsp__[0].string_value));
         else
         CHECK_INPUT_AND_ABORT(CONTROL_SHOULD_NOT_REACH, "Variable has not been declared", get_line_number());
         d_val__.ast = new Name_Ast(*d_vsp__[0].string_value, *var_table_entry, get_line_number());
         delete d_vsp__[0].string_value;
         }
         }
        break;

        case 53:
#line 758 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         int in_name = d_vsp__[0].integer_value;
         Ast* in_ast = new Number_Ast<int>(in_name, int_data_type , get_line_number());
         d_val__.ast = in_ast;
         
         }
         }
        break;

        case 54:
#line 770 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         double d_name = d_vsp__[0].double_value;
         Ast* d_ast = new Number_Ast<double>(d_name, double_data_type , get_line_number());
         d_val__.ast = d_ast;
         }
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



